### ISSUE TITLE
Pod file  QMCVDevelopment not installing

### ISSUE THREAD

**Issue by Kuriakose3** [QuickBlox/q-municate-ios#185]
Pod file  QMCVDevelopment not installing

SSH file created and uploaded in github

When i try `ssh -T git@github.com`
> Hi Kuriakose3! You've successfully authenticated, but GitHub does not provide shell access.
> Macintosh:.ssh kuriakosepious$ ssh -T kuriakose3@github.com

When installing podfile,
```
Pre-downloading: `QMCVDevelopment` from `git.github.com:QuickBlox/QMChatViewController-ios.git`, branch `development`

[!] Error installing QMCVDevelopment
[!] /usr/local/bin/git clone git.github.com:QuickBlox/QMChatViewController-ios.git /var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-11280-1h0j2lw --template= --single-branch --depth 1 --branch development

Cloning into '/var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-11280-1h0j2lw'...
ssh: connect to host git.github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.

```

**Comment by Kuriakose3** [comment]
Verbose file,

```
-> Pre-downloading: `QMCVDevelopment` from `git.github.com:QuickBlox/QMChatViewController-ios.git`, branch `development`
 > Git download
 > Git download
     $ /usr/local/bin/git clone
     git.github.com:QuickBlox/QMChatViewController-ios.git
     /var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-11392-yd75gv
     --template= --single-branch --depth 1 --branch development
     Cloning into '/var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-11392-yd75gv'...
     ssh: connect to host git.github.com port 22: Operation timed out
     fatal: Could not read from remote repository.
     
     Please make sure you have the correct access rights
     and the repository exists.

[!] Error installing QMCVDevelopment
[!] /usr/local/bin/git clone git.github.com:QuickBlox/QMChatViewController-ios.git /var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-11392-yd75gv --template= --single-branch --depth 1 --branch development

Cloning into '/var/folders/1j/dds4dz3d4p1fvw2xbfdj4kh00000gq/T/d20160822-11392-yd75gv'...
ssh: connect to host git.github.com port 22: Operation timed out
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.


/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:122:in `rescue in execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:120:in `execute_command'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/base.rb:154:in `block in executable'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/git.rb:64:in `block in clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:153:in `block in ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:152:in `ui_sub_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/git.rb:62:in `clone'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/git.rb:30:in `download!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/base.rb:82:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:137:in `block in ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:136:in `ui_action'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-downloader-1.0.0/lib/cocoapods-downloader/base.rb:80:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:103:in `download_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:70:in `download_request'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:170:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:153:in `block in uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:180:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:180:in `in_tmpdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:152:in `uncached_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/downloader.rb:39:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:114:in `block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:84:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/abstract_external_source.rb:112:in `pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:479:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:455:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:454:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:453:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by Raikerian** [comment]
@Kuriakose3 were you able to fix this?

**Comment by KuriakosePious** [comment]
@Raikerian  fixed by adding needed files manually .

**Comment by Raikerian** [comment]
If you are still having any other troubles, please let us know by creating a separate issue.

**Comment by Annyjain29** [comment]
From where i can find files which i can add manually ?
